Waltz request reimbursement page
hack4impact-calpoly/ecologistics-portal pull request #77
Opened 2024-02-19 01:12 UTC by lukewaltz

## Developer: Luke Waltz

Closes #49 

### Pull Request Summary

added transaction page with form to request a transaction

### Modifications

- added: \app\reimbursements\page.tsx (contains request reimbursement form)
- added: \components\ui\date-picker.tsx (shadcn date-picker component used in reimbursement form)
- run npm i - i had to import react-hook-form, zod, and radix-ui/react-icons

### Testing Considerations

- it works on npm run dev
- NOTE: there is an issue with the datepicker component's use within the form, I couldn't figure it out so please take a look.

### Pull Request Checklist

- [X] Code is neat, readable, and works
- [X] Comments are appropriate
- [X] The commit messages follows our [guidelines](https://h4i.notion.site/Conventional-Commits-593452ad1179489399ad3bd696ef772a)
- [X] The developer name is specified
- [X] The summary is completed
- [X] Assign reviewers

### Screenshots/Screencast

![image](https://github.com/hack4impact-calpoly/ecologistics-portal/assets/66276398/f89dfca8-a96e-431a-9a6a-ea60bcff900b)
![image](https://github.com/hack4impact-calpoly/ecologistics-portal/assets/66276398/e2816861-e1d5-4c1a-857e-dfa113b051d1)

2024-02-20 02:03 UTC, s-iloo requested changes
Looks great, why don't you checkout the documentation on shadcn with this link https://ui.shadcn.com/docs/components/date-picker
I'm pretty sure if you scroll to the bottom you'll see an example of how they use the datepicker within a form. Pretty sure you're gonna have to hardcode it but should be similar if not identical to how they do it on the docs.

2024-02-20 02:03 UTC, s-iloo commented on src/app/reimbursements/page.tsx
> +                <DatePicker {...field} />
Looks great, why don't you checkout the documentation on shadcn with this link https://ui.shadcn.com/docs/components/date-picker
I'm pretty sure if you scroll to the bottom you'll see an example of how they use the datepicker within a form. Pretty sure you're gonna have to hardcode it but should be similar if not identical to how they do it on the docs.

2024-02-20 02:32 UTC, lukewaltz commented on src/app/reimbursements/page.tsx
> +                <DatePicker {...field} />
![image](https://github.com/hack4impact-calpoly/ecologistics-portal/assets/66276398/dab5e7f3-bee4-4a01-9278-28539dd989a9)
![image](https://github.com/hack4impact-calpoly/ecologistics-portal/assets/66276398/4b437ac8-c7c4-4ac2-b2d7-9dfc30d434b6)

fixed. PR should be updated. Thanks for the help.

2024-02-22 02:59 UTC, s-iloo requested changes
So when I try to enter a transaction amount and then click submit, it doesn't let me submit and highlights the transaction amount field in red. Might be some problem with the types, maybe you have to make the type a string or something? See if you can reproduce the error on your end 

<img width="519" alt="image" src="https://github.com/hack4impact-calpoly/ecologistics-portal/assets/17791908/e4f56afe-543b-4030-abe5-e14ee688e667">

2024-02-23 19:50 UTC, lukewaltz commented on src/app/reimbursements/page.tsx
> +                <DatePicker {...field} />
Hey Ian, I fixed the issue with the transaction amount submissions. PR is updated.

2024-02-24 20:58 UTC, s-iloo approved these changes
Looks great!

2024-02-24 20:59 UTC, merged