feature: organization setup page & route
hack4impact-calpoly/ecologistics-portal pull request #87
Opened 2024-02-22 23:08 UTC by alnhuynh

## Developer: Annes Huynh

Closes #31 

### Pull Request Summary

Created the organization setup page and added setup route.

### Modifications

org-setup.tsx - contains form with specified form fields
organization/routes.tsx - added route

### Testing Considerations

Will need help verifying code was added to the right files & folders.
Vercel deployment issue - needs verification

### Pull Request Checklist

- [x] Code is neat, readable, and works
- [x] Comments are appropriate
- [x] The commit messages follows our [guidelines](https://h4i.notion.site/Conventional-Commits-593452ad1179489399ad3bd696ef772a)
- [x] The developer name is specified
- [x] The summary is completed
- [x] Assign reviewers

### Screenshots/Screencast

{put screenshots of your change, or even better a screencast displaying the functionality} - to be added

2024-02-24 21:39 UTC, ryanhu021 requested changes

2024-02-24 21:39 UTC, ryanhu021 commented on .eslintrc.json
> +    ]
we can run `npm run lint:fix` to convert all CRLF line endings to LF if you're on windows, so we shouldn't need to define a rule here

2024-02-24 21:39 UTC, ryanhu021 commented on src/app/api/organization/route.ts
> +}
we will be connecting this page directly to the clerk API so we don't need a route in our backend. this is because all the organization info will be stored in clerk instead of our backend

2024-02-24 21:39 UTC, ryanhu021 commented on src/app/api/organization/route.ts
> +}
and just fyi: a creation action will typically use an `POST` HTTP method as defined here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods

2024-02-27 03:38 UTC, alnhuynh commented
project not detecting react-hook-form and causing some deployment issues? i think form structure is okay now other than that 
![image](https://github.com/hack4impact-calpoly/ecologistics-portal/assets/76940774/15a5e891-8139-437f-9479-b0c8c003c221)

2024-02-29 03:54 UTC, ryanhu021 approved these changes

2024-02-29 04:06 UTC, merged